version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack
test_script:
- cmd: dotnet test .\Trady.Test\Trady.Test.csproj
artifacts:
- path: Trady.Analysis/bin/Debug/Trady.Analysis.*.nupkg
- path: Trady.Core/bin/Debug/Trady.Core.*.nupkg
- path: Trady.Importer/bin/Debug/Trady.Importer.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: acSSgAlUNA/OCqX0TVICWNqcNcYgBJi01ynOZwXGhTNGVNtRQiv4FIJFsoYnuSgB